export const RESET_INITIAL_STATE = "RESET_INITIAL_STATE";

export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
export const ACCOUNT_LOGOUT = "ACCOUNT_LOGOUT";
export const ACCOUNT_METAMASK_UNAVAILABLE = "ACCOUNT_METAMASK_UNAVAILABLE";
export const ACCOUNT_METAMASK_WRONGNETWORK = "ACCOUNT_METAMASK_WRONGNETWORK";
export const ACCOUNT_METAMASK_NOTREADY = "ACCOUNT_METAMASK_NOTREADY";
export const ACCOUNT_LOADING = "ACCOUNT_LOADING";
export const ACCOUNT_LOADED = "ACCOUNT_LOADED";

export const APP_LOADING = "APP_LOADING";
export const APP_LOADED = "APP_LOADED";
export const APP_TOGGLE_THEME = "APP_TOGGLE_THEME";
export const APP_INITIALIZE = "APP_INITIALIZE";

export const TRANSFER_SHOW = "TRANSFER_SHOW";
export const TRANSFER_HIDE = "TRANSFER_HIDE";
export const TRANSFER_AMOUNT_INPUT = "TRANSFER_AMOUNT_INPUT";
export const TRANSFER_ERROR = "TRANSFER_ERROR";
export const TRANSFER_PENDING_ON = "TRANSFER_PENDING_ON";
export const TRANSFER_PENDING_OFF = "TRANSFER_PENDING_OFF";
export const TRANSFER_COMPLETE = "TRANSFER_COMPLETE";
export const TRANSFER_FAILED = "TRANSFER_FAILED";

export const TOKENS_FILTER = "TOKENS_FILTER";
export const TOKENS_CLEAR_FILTER = "TOKENS_CLEAR_FILTER";
export const TOKENS_LOAD = "TOKENS_LOAD";

export const TRANSFERS_FILTER = "TRANSFERS_FILTER";
export const TRANSFERS_CLEAR_FILTER = "TRANSFERS_CLEAR_FILTER";
export const TRANSFERS_LOAD = "TRANSFERS_LOAD";

export const ACCOUNT_ORDERS_FILTER = "ACCOUNT_ORDERS_FILTER";
export const ACCOUNT_ORDERS_CLEAR_FILTER = "ACCOUNT_ORDERS_CLEAR_FILTER";
export const ACCOUNT_ORDERS_LOAD = "ACCOUNT_ORDERS_LOAD";

export const MARKETS_FILTER = "MARKETS_FILTER";
export const MARKETS_CLEAR_FILTER = "MARKETS_CLEAR_FILTER";
export const MARKETS_LOAD = "MARKETS_LOAD";

export const ACCOUNT_TRADES_FILTER = "ACCOUNT_TRADES_FILTER";
export const ACCOUNT_TRADES_CLEAR_FILTER = "ACCOUNT_TRADES_CLEAR_FILTER";
export const ACCOUNT_TRADES_LOAD = "ACCOUNT_TRADES_LOAD";
