export const RESET_INITIAL_STATE = "RESET_INITIAL_STATE";

export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
export const ACCOUNT_LOGOUT = "ACCOUNT_LOGOUT";
export const ACCOUNT_METAMASK_UNAVAILABLE = "ACCOUNT_METAMASK_UNAVAILABLE";
export const ACCOUNT_METAMASK_WRONGNETWORK = "ACCOUNT_METAMASK_WRONGNETWORK";
export const ACCOUNT_LOADING = "ACCOUNT_LOADING";
export const ACCOUNT_LOADED = "ACCOUNT_LOADED";

export const APP_LOADING = "APP_LOADING";
export const APP_LOADED = "APP_LOADED";
export const APP_TOGGLE_THEME = "APP_TOGGLE_THEME";
export const APP_INITIALIZE = "APP_INITIALIZE";

export const TOKEN_FILTER = "TOKEN_FILTER";
export const TOKEN_LOAD = "TOKEN_LOAD";

export const MODAL_SHOW = "MODAL_SHOW";
export const MODAL_HIDE = "MODAL_HIDE";
